version: "3.9"
services:
  influxdb:
    image: influxdb:2.7
    restart: unless-stopped
    ports:
      - "8086:8086"          # UI + API
    volumes:
      - ./influx-data:/var/lib/influxdb2
      - ./influx-config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=your_password
      - DOCKER_INFLUXDB_INIT_ORG=realwx
      - DOCKER_INFLUXDB_INIT_BUCKET=weather_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=your_secret_token
